import { OnStartResult, Plugin, PluginBuild } from 'esbuild';
import { readdir, writeFile } from 'node:fs/promises';
import { basename } from 'node:path';
import { promisify } from 'node:util';
import Spritesmith from 'spritesmith';
import Handlebars from 'handlebars';

const NAMESPACE = 'esbuild-plugin-spritesmith';

export type Options = {
	input_folder: string,
	output_css: string,
	output_image: string,
	output_image_url: string,
}

export function spritesmith(options: Options): Plugin {
	const { input_folder, output_css, output_image, output_image_url } = options;

	return {
		name: NAMESPACE,
		setup(build: PluginBuild) {
			build.onStart(async (): Promise<OnStartResult> => {
				const sprite_paths = (await readdir(input_folder))
					.filter(path => path.endsWith('.png'))
					.map(path => input_folder + path);


				const { coordinates, image } = await promisify(Spritesmith.run)({
					src: sprite_paths
				});

				const sprites = Object.entries(coordinates).map(([name, coords]) => {
					return {
						name: basename(name, '.png').replaceAll('_', ':'),
						...coords
					};
				});

				// make the css
				const css = Handlebars.compile(`
					/* This file is generated by @repo/esbuild-plugin-spritesmith */
					.sprite {
						background-image: url(${output_image_url});
					}
					{{#each sprites}}
					.sprite.sp-{{name}} {
						background-position: -{{x}}px -{{y}}px;
						width: {{width}}px;
						height: {{height}}px;
					}
					{{/each}}
					`)({ sprites });


				await writeFile(output_css, css, {
					encoding: 'utf-8'
				});
				await writeFile(output_image, image);
				console.info(`SMTH: wrote ${sprite_paths.length} sprites`);
				return {};
			});
		}
	}
}
