// Load in dependencies
import { readdirSync, writeFileSync } from 'node:fs';
import { basename } from 'node:path';
import Spritesmith from 'spritesmith';
import handlebars from 'handlebars';

const ctr = 'src/webfiles/ctr';
const ctr_images = ctr + '/images';
const esbuild_ctr = '@/webfiles/ctr';
const sprite_paths = readdirSync(ctr_images + '/sprites')
	.filter(path => path.endsWith('.png'))
	.map(path => ctr_images + '/sprites/' + path);

// Generate our spritesheet
Spritesmith.run({
	src: sprite_paths
}, function handleResult(err, result) {
	if (err) {
		console.error(err);
		return;
	}
	const { coordinates, image } = result;

	const sprites = Object.entries(coordinates).map(([name, coords]) => {
		return {
			name: basename(name, '.png').replaceAll('_', ':'),
			...coords
		};
	});

	// make the css
	const res = handlebars.compile(`
		/* This file is generated by scripts/sprites.ts */
		.sprite {
			background-image: url(${esbuild_ctr}/images/sprites.png);
		}
		{{#each sprites}}
		.sprite.sp-{{name}} {
			background-position: -{{x}}px -{{y}}px;
			width: {{width}}px;
			height: {{height}}px;
		}
		{{/each}}
		`)({ sprites });

	writeFileSync(ctr + '/css/sprites.css', res, {
		encoding: 'utf-8'
	});
	writeFileSync(ctr + '/images/sprites.png', image);
	console.info(`success: wrote ${sprite_paths.length} sprites`);
});
