name: "juxtaposition-dev"

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  mongo:
    image: mongo:8.0
    restart: unless-stopped
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"

    # This funky stuff is needed for making a replicaset
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - "mongo_data:/data/db"
      - "mongo_config:/data/configdb"
  # mc alias set local http://localhost:9000 minioadmin minioadmin
  # mc mb --ignore-existing local/miiverse
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DOMAIN: minio
    command: server /data --console-address ":9001"
    volumes:
      - "minio_data:/data"
    ports:
      - 127.0.0.1:9000:9000
      - 127.0.0.1:9001:9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      retries: 3
      timeout: 5s
    networks:
      default:
        aliases:
          # vhost-style bucket naming
          - miiverse.minio
  minio-setup:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DOMAIN: minio
      BUCKET: miiverse
    volumes:
      - "./create-buckets.sh:/etc/minio/create-buckets.sh"
    entrypoint: "/etc/minio/create-buckets.sh"

  proxy:
    image: mitmproxy/mitmproxy
    command: > 
      mitmweb -v --mode regular@8888
      -s /data/mitmproxy-local.py
      --web-host 0.0.0.0 --set web_password=letmein
      -k --set tls_version_client_min=UNBOUNDED --set tls_version_server_min=UNBOUNDED 
      --set key_size=1024
    ports:
      - 8888:8888
      - 127.0.0.1:8081:8081
    volumes:
      - "./mitmproxy-local.py:/data/mitmproxy-local.py"
      - "./mitmproxy-data/:/home/mitmproxy/.mitmproxy/"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  account:
    image: ghcr.io/pretendonetwork/account:sha-99aec60
    restart: unless-stopped
    ports:
      - "8123:8123" # grpc
    links:
      - mongo
    environment:
      PN_ACT_CONFIG_REDIS_URL: redis://redis:6379
      PN_ACT_CONFIG_HTTP_PORT: 8000
      PN_ACT_CONFIG_GRPC_PORT: 8123
      PN_ACT_CONFIG_MONGO_CONNECTION_STRING: "mongodb://mongo:27017/account?directConnection=true"
      PN_ACT_CONFIG_S3_ENDPOINT: "http://minio:9000"
      PN_ACT_CONFIG_S3_REGION: "us-east-1"
      PN_ACT_CONFIG_S3_BUCKET: "miiverse"
      PN_ACT_CONFIG_S3_ACCESS_KEY: "minioadmin"
      PN_ACT_CONFIG_S3_ACCESS_SECRET: "minioadmin"
      PN_ACT_CONFIG_CDN_BASE_URL: "http://cdn.pretendo.cc/miiverse"
      PN_ACT_CONFIG_AES_KEY: "1234567812345678123456781234567812345678123456781234567812345678"
      PN_ACT_CONFIG_GRPC_MASTER_API_KEY_ACCOUNT: "12345678123456781234567812345678"
      PN_ACT_CONFIG_GRPC_MASTER_API_KEY_API: "12345678123456781234567812345678"

  friends:
    image: ghcr.io/pretendonetwork/friends:sha-5560c1d
    restart: unless-stopped
    ports:
      - "8124:8124" # grpc
    environment:
      PN_FRIENDS_CONFIG_DATABASE_URI: "postgres://todo@localhost"
      PN_FRIENDS_CONFIG_AES_KEY: "1234567812345678123456781234567812345678123456781234567812345678"
      PN_FRIENDS_CONFIG_GRPC_API_KEY: "12345678123456781234567812345678"
      PN_FRIENDS_GRPC_SERVER_PORT: 8124
      PN_FRIENDS_AUTHENTICATION_SERVER_PORT: 60000
      PN_FRIENDS_SECURE_SERVER_HOST: "friends"
      PN_FRIENDS_SECURE_SERVER_PORT: 60001
      PN_FRIENDS_ACCOUNT_GRPC_HOST: "account"
      PN_FRIENDS_ACCOUNT_GRPC_PORT: 8123
      PN_FRIENDS_ACCOUNT_GRPC_API_KEY: "12345678123456781234567812345678"

volumes:
  mongo_data:
  mongo_config:
  redis_data:
  minio_data:
